#+TITLE: OM's Dotfiles

* Table of contents :toc:
- [[#what-are-dotfiles][What Are Dotfiles]]
- [[#availabe-configs][Availabe Configs]]
- [[#i3wm][I3WM]]
- [[#notes][NOTES]]
- [[#who-am-i][Who Am I?]]
- [[#omar-mohamed-on-the-web][Omar Mohamed On The Web]]

* What Are Dotfiles

Dotfiles are the customization files that are used to personalize your Linux or other Unix-based system.  You can tell that a file is a dotfile because the name of the file will begin with a period–a dot!  The period at the beginning of a filename or directory name indicates that it is a hidden file or directory.  This repository contains my personal dotfiles.  They are stored here for convenience so that I may quickly access them on new machines or new installs.  Also, others may find some of my configurations helpful in customizing their own dotfiles.

* Availabe Configs

| [[https://github.com/Coptan99/Dotfiles/tree/master/.config/emacs][Emacs]] | [[https://github.com/Coptan99/Dotfiles/tree/master/.config/nvim][Neovim]]   |
| [[https://github.com/Coptan99/Dotfiles/blob/master/.zshrc][Zsh]]   | [[https://github.com/Coptan99/Dotfiles/blob/master/.tmux.conf][Tmux]]     |
| i3    | i3status |

* TODO I3WM

I3 is a tiling window manager that is stripped down to its absolute minimum.
If you were using a desktop environment and you want to switch to i3 you should install soe packages firstly, such as:

1. *dmenu* Which is the dynamic menu for X.
2. *lxqt-notificationd* which is a notification daemon which without it you will find some bugs with notifications in apps in other workspaces.
3. *nm-applet* Which we will use to manage wifi networks. 
4. *i3status* To be able to configure the statusbar
5. *nitrogen* Which we will use to display a wallpaper as a background for our workspaces instead of our login manager wallpaper.
6. *scrot* which we will use for taking screenshots.
7. Add configuration for brightness settings.

* NOTES
- Install *shell-color-scripts* using /yay/ or /paru/

* Who Am I?

I am Omar Mohamed (OM), a Computer Science (CS) student at October 6 University (also O6U), also a Junior Frontend Developer who spends time in configuring Linux for more productivity or keep searching for new technologies.

* Omar Mohamed On The Web

+ [[https://linktr.ee/Coptan][Linktree]]
